.TH GWIBBER 1 "JULY 2010" Linux "User Manuals"
.SH NAME
Gwibber \- Microblogging client for GNOME
.SH SYNOPSIS
.B gwibber-accounts [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B gwibber-accounts
handles accounts for gwibber. You should not run this binary separately unless
you want to debug any issues with gwibber.
.SH OPTIONS
.IP "-h, --help"
Show help message and exit.
.IP "-d, --debug"
Log debug messages.
.SH BUGS
Please report all bugs to the Gwibber bug tracker:
http://launchpad.net/gwibber
.SH AUTHOR
Kartik Mistry <kartik@debian.org>

Copyright 2010. Licensed under a Creative Commons Attribution-ShareAlike License <http://creativecommons.org/licenses/by-sa/3.0/>
